### PR TITLE
Please accept the pull request to improve API readability and ergonomics

### PR DESCRIPTION
**Pull request by kLeZ**
Hi. I used your library to animate some screens in my puppy projects and found an area of improvement that I implemented and now gently pushing to you.

Although the code is well written and easily understandable, I would have preferred not to dive the code to understand that a parameter like "duration" is used as "duration in seconds".

In fact, it is not immediately clear that the duration is expressed in seconds in all the code except for a javadoc sunk in the class hierarchy and overridden in the children classes.

I think this is a code maturity feature, and it surely is a best practice to specify measure units in the name of variable (or parameter, for that matter) when the type cannot completely make its usage and understanding clear.

So I made this simple and straightforward change and present to you the request to integrate it in the main library code.

Thanks.
kLeZ.

### CODE REVIEW

**Comment by Frosty-J** [comment]
`durationInSeconds` is a bit of an awkward variable name, in my view. It shouldn't be surprising that the durations are measured in seconds, as libGDX itself always measures times in seconds when they are of type `float`, and seconds are the only unit that it could be in the example (see the README). However, improving documentation/comments in this regard is never a bad thing. Let's see what crykn thinks.

**Comment by crykn** [comment]
Hey @kLeZ,

Thanks for bringing this up! As @Frosty-J said, the combination of being a libGDX extension and using a float kinda implies that the duration is in seconds. I'm not really a fan of the name `durationInSeconds`, but I agree that this should be documented better and on every constructor, not just the parent classes ones.

**Comment by kLeZ** [comment]
Hi @crykn thanks for merging!
I can agree the variable name isn't the best (programmers are poor at naming variables, I guess) but I think I can risk a poor variable name if the gain is the better understanding of the code.
Perhaps the problem could be solved with a different API design approach, such as using java.time.Duration?
In fact, I think that even LibGDX itself should be using those better types in their public APIs, if only the backwards compatibility wasn't an issue for them.
I can work that out if you feel confident in the change.
Regarding the current PR, thanks for accepting!

**Comment by crykn** [comment]
I think keeping it in line with the libGDX API is the best approach. 

> Perhaps the problem could be solved with a different API design approach, such as using java.time.Duration?

`java.time.Duration` would not only break backwards compatibility, it isn't even supported on all platforms (since it was introduced with Java 8). I also doubt that it would add much use, because converting the delta time is probably not needed very often, not to speak of the garbage produced by using objects instead of primitive types.

**Pull request merged**
